sonar.projectKey=Alphaexplora-Sandbox_alphatest-12345-fe
sonar.projectName=alphatest-12345-frontend
sonar.sources=src
sonar.tests=src,tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx